icons = {
    "Quasarroll/Upscale": "🧩 Quasarroll Studio/✨ Essential/🔍 Upscale",
    "Quasarroll/Model Merge": "🧩 Quasarroll Studio/✨ Essential/⛏️ Model Merge",
    "Quasarroll/Utils/Logic": "🧩 Quasarroll Studio/🛠️ Utils/🔀 Logic",
    "Quasarroll/Utils/Conditional": "🧩 Quasarroll Studio/🛠️ Utils/🔀 Conditional", 
    "Quasarroll/Utils/Process": "🧩 Quasarroll Studio/🛠️ Utils/🔂 Process",
    "Quasarroll/Utils/Index": "🧩 Quasarroll Studio/🛠️ Utils/🔢 Index",
    "Quasarroll/Utils/Conversion": "🧩 Quasarroll Studio/🛠️ Utils/🔧 Conversion",
    "Quasarroll/Utils/Random": "🧩 Quasarroll Studio/🛠️ Utils/🎲 Random",
    "Quasarroll/Utils/Text": "🧩 Quasarroll Studio/🛠️ Utils/🔤 Text",    
    "Quasarroll/Utils/Other": "🧩 Quasarroll Studio/🛠️ Utils/⚙️ Other",
    "Quasarroll/LoRA": "🧩 Quasarroll Studio/✨ Essential/💊 LoRA",
    "Quasarroll/ControlNet": "🧩 Quasarroll Studio/✨ Essential/🕹️ ControlNet",
    "Quasarroll/XY Grid": "🧩 Quasarroll Studio/✨ Essential/📉 XY Grid",
    "Quasarroll/SDXL": "🧩 Quasarroll Studio/✨ Essential/🌟 SDXL",
    "Quasarroll/List": "🧩 Quasarroll Studio/✨ Essential/📜 List",
    "Quasarroll/List/IO": "🧩 Quasarroll Studio/✨ Essential/📜 List/⌨️ IO",    
    "Quasarroll/List/Utils": "🧩 Quasarroll Studio/✨ Essential/📜 List/🛠️ Utils",      
    "Quasarroll/Aspect Ratio": "🧩 Quasarroll Studio/✨ Essential/🔳 Aspect Ratio",
    "Quasarroll/Pipe/Module": "🧩 Quasarroll Studio/✨ Essential/🎷 Pipe/✈️ Module",
    "Quasarroll/Pipe/Image": "🧩 Quasarroll Studio/✨ Essential/🎷 Pipe/🛩️ Image",
    "Quasarroll/Pipe/Bus": "🧩 Quasarroll Studio/✨ Essential/🎷 Pipe/🚌 Bus",    
    "Quasarroll/Pipe": "🧩 Quasarroll Studio/✨ Essential/🎷 Pipe",
    "Quasarroll/Graphics/Text": "🧩 Quasarroll Studio/👾 Graphics/🔤 Text",
    "Quasarroll/Graphics/Layout": "🧩 Quasarroll Studio/👾 Graphics/🌁 Layout",
    "Quasarroll/Graphics/Template": "🧩 Quasarroll Studio/👾 Graphics/📱 Template",
    "Quasarroll/Graphics/Filter": "🧩 Quasarroll Studio/👾 Graphics/🎨 Filter",
    "Quasarroll/Graphics/Pattern": "🧩 Quasarroll Studio/👾 Graphics/🌈 Pattern",
    "Quasarroll/Graphics/Shape": "🧩 Quasarroll Studio/👾 Graphics/🟣 Shape",
    "Quasarroll/Graphics/3D": "🧩 Quasarroll Studio/👾 Graphics/3D",
    "Quasarroll/Graphics/Utilty": "🧩 Quasarroll Studio/👾 Graphics/🔧 Utility",
    "Quasarroll/Workflow": "🧩 Quasarroll Studio/✨ Essential/Workflow",     
    "Quasarroll/Essential/Core": "🧩 Quasarroll Studio/✨ Essential/📦 Core",
    "Quasarroll/Essential/Legacy": "🧩 Quasarroll Studio/✨ Essential/💀 Legacy",
    "Quasarroll/Animation/Camera": "🧩 Quasarroll Studio/🎥 Animation/🎦 Camera",
    "Quasarroll/Animation/Utils": "🧩 Quasarroll Studio/🎥 Animation/🛠️ Utils",
    "Quasarroll/Animation/Schedule": "🧩 Quasarroll Studio/🎥 Animation/📋 Schedule",
    "Quasarroll/Animation/Schedulers": "🧩 Quasarroll Studio/🎥 Animation/📑 Schedulers",
    "Quasarroll/Animation/Prompt": "🧩 Quasarroll Studio/🎥 Animation/📝 Prompt",
    "Quasarroll/Animation/Legacy": "🧩 Quasarroll Studio/🎥 Animation/💀 Legacy",
    "Quasarroll/Animation/Interpolate": "🧩 Quasarroll Studio/🎥 Animation/🔢 Interpolate",
    "Quasarroll/Animation/IO": "🧩 Quasarroll Studio/🎥 Animation/⌨️ IO",
}
